name: compaz_radio
description: COMPAZ RADIO .
   
publish_to: "none"
  
version: 3.2.0
 
environment:
  sdk: ">=3.5.1 <4.2.0"
  # flutter: ^3.16.2
            
dependencies:
  flutter:
    sdk: flutter
     
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: 2.1.1
  flutter_screenutil: 5.9.3
  google_fonts: ^6.2.1
  assets_audio_player: ^3.1.1
  animate_icons: ^2.0.0
  url_launcher: ^6.3.1
  glassmorphism: ^3.0.0
  dropdown_button2: ^2.3.9
  google_mobile_ads: ^5.3.1
  onesignal_flutter: ^5.2.9
  flutter_share: ^2.0.0
  rating_dialog: ^2.0.4
  store_redirect: ^2.0.1
  dynamic_themes: ^1.1.0
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  miniplayer: ^1.0.1
  flutter_inappwebview: ^6.1.5
  video_player: ^2.9.2
  chewie: ^1.8.5
  win32: ^5.5.4 
  lottie: ^2.3.2
  webview_flutter: ^4.4.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Agregado

# Configuración del icono
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"  # Asegúrate de poner tu icono en esta ruta
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"  # Puedes cambiar el color de fondo
  adaptive_icon_foreground: "assets/images/app_icon.png"  # El mismo icono o uno diferente para Android
  remove_alpha_ios: true  # Importante para iOS

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/video_image/